<?php
 return array (
  'code' => 'en',
  'region' => 'en',
  'name' => 'Multi language notifications',
  'author' => 'أغضان . twigs',
  'link' => 'https://twigs.cc',
  'date' => '16/01/2025',
  'data' => 
  array (
    'registration' => '<p style="text-align:right;"><strong>مرحباً</strong></p><p style="text-align:right;">تم تسجيلك بنجاح في أغصان، يمكنك تسجيل الدخول من هنا <a href="{site.link}">{site.link}</a></p><p><strong>Hello!</strong></p><p>You have been successfully registered at <strong>Twigs</strong>. You can now login to our site at <a href="{site.link}">{site.link}</a>.</p>',
    'activation' => '<p style="text-align:right;"><strong>مرحباً</strong></p><p style="text-align:right;"><span style="font-size:14px;">تم تسجيلك بنجاح في أغصان، فضلاً قم بتنشيط حسابك بالضغط على الرابط في الأسفل</span></p><p style="text-align:right;"><a href="{user.activation}">{user.activation}</a></p><p><strong>Hello!</strong></p><p><span style="font-size:14px;">You have been successfully registered at <strong>Twigs</strong>. To login you will have to activate your account by clicking the URL below.</span></p><p><a href="{user.activation}">{user.activation}</a></p>',
    'success' => '<p style="text-align:right;"><strong>مرحباً</strong></p><p style="text-align:right;">تم تفعيل حسابك بنجاح في أغصان.</p><p><strong>Hello!</strong></p><p>Your account has been successfully activated at <strong>Twigs</strong></p>',
    'passwordreset' => '<p style="text-align:right;"><strong>مرحباً</strong></p><p style="text-align:right;"><strong>تم طلب إعادة ضبط كلمة المرور لحسابك على منصة أغصان</strong>. -إذا لم تقم بهذا، فضلاً تجاهل هذا البريد الإلكتروني- ولإعادة ضبط كلمة المرور فضلاً اضغط على الرابط في الأسفل</p><p style="text-align:right;"><a href="{user.activation}"><strong>اضغط هنا لإعادة ضبط كلمة المرور</strong></a></p><p style="text-align:right;">إذا لم تستطع الضغط على الرابط، فضلاً انسخ الرابط في الاسفل والصقه في المتصفح</p><p style="text-align:right;"><a href="{user.activation}">{user.activation}</a></p><p><strong>Hello!</strong></p><p><strong>A request to reset your password was made.</strong>&nbsp;If you&nbsp;<strong>did not</strong>&nbsp;make this request, please ignore and delete this email otherwise click the link below to reset your password.</p><p><a href="{user.activation}"><strong>Click here to reset your password.</strong></a></p><p>If you cannot click on the link above, simply copy &amp; paste the following link into your browser.</p><p><a href="{user.activation}">{user.activation}</a></p>',
    'teaminvitation' => '<p style="text-align:right;"><strong>مرحباً</strong></p><p style="text-align:right;">تلقيت دعوة للإنضمام لفريقنا في <strong>أغصان</strong>. لقبول الدعوة اضغط على الرابط في الأسفل.</p><p style="text-align:right;"><a href="{user.invite}">{user.invite}</a></p><p><strong>Hello!</strong></p><p>You have been invited to join our team at <strong>Twigs</strong>. To accept the invitation, please click the link below.</p><p><a href="{user.invite}">{user.invite}</a></p>',
    'verify2fa' => '<p style="text-align:right;"><strong>مرحباً</strong></p><p style="text-align:right;">تلقينا طلباً لإلغاء التحقق الثنائي (2FA) على حسابك في <strong>أغصان. </strong>إذا لم تقم بهذا الطلب، فضلاً تجاهل هذا البريد الإلكتروني أو اضغط على الرابط في الأسفل لإلغاء التحقق الثنائي على حسابك.</p><p style="text-align:right;"><a href="{user.activation}"><strong>اضغط هنا</strong></a></p><p style="text-align:right;">إذا لم تتمكن من الضغط على الرابط، انسخ الرابط في الأسفل والصقه في المتصفح&nbsp;</p><p style="text-align:right;"><a href="{user.activation}">{user.activation}</a></p><p><strong>Hello!</strong></p><p>A request was made to reset and disable 2FA on your account. If you <strong>did not</strong> make this request, please ignore and delete this email otherwise click the link below to reset it.</p><p><a href="{user.activation}"><strong>Click here to reset.</strong></a></p><p>If you cannot click on the link above, simply copy &amp; paste the following link into your browser.</p><p><a href="{user.activation}">{user.activation}</a></p>',
    'newip' => '<p style="text-align:right;"><strong>مرحباً</strong></p><p style="text-align:right;">تم تسجيل الدخول لحسابك من عنوان IP جديد. إذا لم تستطع التعرف على هذا الدخول، فضلاً قم بتغيير كلمة المرور في حسابك في <strong>أغصان </strong>فوراً.</p><p style="text-align:right;"><strong>IP عنوان</strong>: {ip}</p><p style="text-align:right;"><strong>الموقع</strong>: {location}</p><p style="text-align:right;"><strong>الوقت والتاريخ</strong>: {datetime}</p><p><strong>Hello!</strong></p><p>A new login has been made from a new IP address. If this wasn\'t you, please secure your account immediately.&nbsp;</p><p><strong>IP Address</strong>: {ip}</p><p><strong>Location</strong>: {location}</p><p><strong>Date &amp; Time</strong>: {datetime}</p>',
  ),
);